/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["HealthController_checkHealth"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/health/deploy-db": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["HealthController_deployDatabase"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/contratadas": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Listar contratadas
     * @description Lista todas as contratadas com filtros opcionais
     */
    get: operations["ContratadaController_listarContratadas"];
    put?: never;
    /**
     * Criar nova contratada
     * @description Cria uma nova empresa contratada no sistema
     */
    post: operations["ContratadaController_criarContratada"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/contratadas/estatisticas": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Obter estatísticas das contratadas
     * @description Retorna estatísticas gerais das contratadas e colaboradores vinculados
     */
    get: operations["ContratadaController_obterEstatisticas"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/contratadas/buscar": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Buscar contratadas por nome
     * @description Busca contratadas por nome (limitado a 10 resultados)
     */
    get: operations["ContratadaController_buscarPorNome"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/contratadas/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Obter contratada por ID
     * @description Retorna os dados de uma contratada específica
     */
    get: operations["ContratadaController_obterContratada"];
    /**
     * Atualizar contratada
     * @description Atualiza os dados de uma contratada existente
     */
    put: operations["ContratadaController_atualizarContratada"];
    post?: never;
    /**
     * Excluir contratada
     * @description Exclui uma contratada do sistema (apenas se não houver colaboradores vinculados)
     */
    delete: operations["ContratadaController_excluirContratada"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/estoque/posicao": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Relatório de posição de estoque
     * @description Gera relatório detalhado da posição atual do estoque com filtros opcionais
     */
    get: operations["EstoqueController_obterPosicaoEstoque"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/estoque/kardex/{almoxarifadoId}/{tipoEpiId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Obter kardex de item
     * @description Retorna o kardex (histórico de movimentações) de um item específico
     */
    get: operations["EstoqueController_obterKardex"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/estoque/analise-giro": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Análise de giro de estoque
     * @description Analisa o giro de estoque por período para identificar itens com movimentação rápida ou lenta
     */
    get: operations["EstoqueController_obterAnaliseGiro"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/estoque/ajuste-direto": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Realizar ajuste direto de estoque
     * @description Executa um ajuste direto na quantidade de um item específico
     */
    post: operations["EstoqueController_realizarAjusteDirecto"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/estoque/ajuste-direto/simular": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Simular ajuste de estoque
     * @description Simula um ajuste de estoque para visualizar o impacto antes da execução
     */
    post: operations["EstoqueController_simularAjuste"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/estoque/inventario": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Executar inventário completo
     * @description Processa múltiplos ajustes de inventário baseados na contagem física
     */
    post: operations["EstoqueController_executarInventario"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/estoque/inventario/validar-divergencias": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Validar divergências de inventário
     * @description Compara contagens de inventário com saldos do sistema e identifica divergências
     */
    post: operations["EstoqueController_validarDivergenciasInventario"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/estoque/ajustes/historico": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Histórico de ajustes de estoque
     * @description Lista o histórico de ajustes realizados com filtros opcionais
     */
    get: operations["EstoqueController_obterHistoricoAjustes"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/estoque/resumo": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Resumo geral do estoque
     * @description Retorna indicadores e métricas gerais do estoque
     */
    get: operations["EstoqueController_obterResumoEstoque"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/estoque/alertas": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Alertas de estoque
     * @description Lista itens que requerem atenção (estoque baixo, crítico ou zerado)
     */
    get: operations["EstoqueController_obterAlertasEstoque"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/fichas-epi": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Listar fichas de EPI
     * @description Lista fichas com filtros opcionais e paginação
     */
    get: operations["FichasEpiController_listarFichas"];
    put?: never;
    /**
     * Criar nova ficha de EPI
     * @description Cria uma nova ficha de EPI para um colaborador específico
     */
    post: operations["FichasEpiController_criarFicha"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/fichas-epi/criar-ou-ativar": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Criar ou ativar ficha de EPI
     * @description Cria nova ficha ou ativa uma existente inativa para a mesma combinação
     */
    post: operations["FichasEpiController_criarOuAtivarFicha"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/fichas-epi/estatisticas": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Estatísticas das fichas de EPI
     * @description Retorna estatísticas gerais das fichas por almoxarifado
     */
    get: operations["FichasEpiController_obterEstatisticas"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/fichas-epi/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Buscar ficha por ID
     * @description Retorna os detalhes completos de uma ficha de EPI
     */
    get: operations["FichasEpiController_obterFicha"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/fichas-epi/{id}/ativar": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Ativar ficha de EPI
     * @description Ativa uma ficha que estava inativa ou suspensa
     */
    put: operations["FichasEpiController_ativarFicha"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/fichas-epi/{id}/inativar": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Inativar ficha de EPI
     * @description Inativa uma ficha que não possui entregas ativas
     */
    put: operations["FichasEpiController_inativarFicha"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/fichas-epi/{id}/suspender": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Suspender ficha de EPI
     * @description Suspende uma ficha temporariamente com motivo opcional
     */
    put: operations["FichasEpiController_suspenderFicha"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/fichas-epi/{id}/entregas": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Listar entregas da ficha
     * @description Lista todas as entregas realizadas para uma ficha específica
     */
    get: operations["FichasEpiController_listarEntregasFicha"];
    put?: never;
    /**
     * Criar nova entrega
     * @description Registra uma nova entrega de EPI para uma ficha específica
     */
    post: operations["FichasEpiController_criarEntrega"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/fichas-epi/entregas/validar": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Validar se entrega é permitida
     * @description Verifica se uma entrega pode ser realizada (ficha ativa, estoque disponível)
     */
    post: operations["FichasEpiController_validarEntrega"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/fichas-epi/colaborador/{colaboradorId}/entregas": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Listar entregas do colaborador
     * @description Lista todas as entregas de um colaborador específico
     */
    get: operations["FichasEpiController_listarEntregasColaborador"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/fichas-epi/colaborador/{colaboradorId}/posse-atual": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Posse atual do colaborador
     * @description Retorna todos os EPIs atualmente em posse do colaborador
     */
    get: operations["FichasEpiController_obterPosseAtual"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/fichas-epi/entregas/{entregaId}/devolucao": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Processar devolução de itens
     * @description Processa a devolução de um ou mais itens de uma entrega
     */
    post: operations["FichasEpiController_processarDevolucao"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/fichas-epi/entregas/{entregaId}/devolucao/validar": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Validar se devolução é permitida
     * @description Verifica se os itens podem ser devolvidos
     */
    post: operations["FichasEpiController_validarDevolucao"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/fichas-epi/entregas/{entregaId}/devolucao/cancelar": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Cancelar devolução de itens
     * @description Cancela uma devolução recente (até 72 horas) reverterendo o status
     */
    post: operations["FichasEpiController_cancelarDevolucao"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/fichas-epi/entregas/{entregaId}/devolucao/validar-cancelamento": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Validar cancelamento de devolução
     * @description Verifica se uma devolução pode ser cancelada (prazo, status)
     */
    get: operations["FichasEpiController_validarCancelamentoDevolucao"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/fichas-epi/devolucoes/historico": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Histórico de devoluções
     * @description Lista o histórico de devoluções com filtros opcionais
     */
    get: operations["FichasEpiController_obterHistoricoDevolucoes"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/fichas-epi/devolucoes/cancelamentos/historico": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Histórico de cancelamentos de devolução
     * @description Lista o histórico de cancelamentos de devolução
     */
    get: operations["FichasEpiController_obterHistoricoCancelamentosDevolucao"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/notas-movimentacao": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Listar notas de movimentação
     * @description Lista notas com filtros opcionais e paginação
     */
    get: operations["NotasMovimentacaoController_listarNotas"];
    put?: never;
    /**
     * Criar nova nota de movimentação em rascunho
     * @description Cria uma nova nota de movimentação no status RASCUNHO para posterior adição de itens
     */
    post: operations["NotasMovimentacaoController_criarNota"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/notas-movimentacao/rascunhos": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Listar notas em rascunho
     * @description Lista apenas as notas no status RASCUNHO do usuário atual
     */
    get: operations["NotasMovimentacaoController_listarRascunhos"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/notas-movimentacao/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Buscar nota por ID
     * @description Retorna os detalhes completos de uma nota, incluindo itens
     */
    get: operations["NotasMovimentacaoController_obterNota"];
    /**
     * Atualizar observações da nota
     * @description Atualiza apenas as observações de uma nota em rascunho
     */
    put: operations["NotasMovimentacaoController_atualizarNota"];
    post?: never;
    /**
     * Excluir nota em rascunho
     * @description Exclui uma nota que está no status RASCUNHO
     */
    delete: operations["NotasMovimentacaoController_excluirNota"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/notas-movimentacao/{id}/itens": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Adicionar item à nota
     * @description Adiciona um novo item a uma nota em rascunho
     */
    post: operations["NotasMovimentacaoController_adicionarItem"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/notas-movimentacao/{id}/itens/{tipoEpiId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Atualizar quantidade do item
     * @description Atualiza a quantidade de um item específico na nota
     */
    put: operations["NotasMovimentacaoController_atualizarQuantidadeItem"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/notas-movimentacao/{id}/itens/{itemId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Remover item da nota
     * @description Remove um item específico de uma nota em rascunho
     */
    delete: operations["NotasMovimentacaoController_removerItem"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/notas-movimentacao/{id}/concluir": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Concluir nota de movimentação
     * @description Processa uma nota em rascunho, criando movimentações e atualizando estoque
     */
    post: operations["NotasMovimentacaoController_concluirNota"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/notas-movimentacao/{id}/cancelar": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Cancelar nota de movimentação
     * @description Cancela uma nota, gerando estornos se necessário
     */
    post: operations["NotasMovimentacaoController_cancelarNota"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/notas-movimentacao/{id}/validar-cancelamento": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Validar se nota pode ser cancelada
     * @description Verifica se uma nota pode ser cancelada e retorna informações sobre o impacto
     */
    get: operations["NotasMovimentacaoController_validarCancelamento"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/relatorios/dashboard": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Dashboard principal
     * @description Retorna indicadores gerais, alertas e métricas para o painel principal
     */
    get: operations["RelatoriosController_obterDashboard"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/relatorios/conformidade": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Relatório de conformidade
     * @description Lista colaboradores e seu status de conformidade com EPIs obrigatórios
     */
    get: operations["RelatoriosController_relatorioConformidade"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/relatorios/uso-epis": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Relatório de uso de EPIs
     * @description Analisa padrões de uso, tempo médio e condições de devolução
     */
    get: operations["RelatoriosController_relatorioUsoEpis"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/relatorios/movimentacoes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Relatório de movimentações
     * @description Lista todas as movimentações de estoque com filtros detalhados
     */
    get: operations["RelatoriosController_relatorioMovimentacoes"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/relatorios/saude-sistema": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Saúde do sistema
     * @description Monitora o status geral do sistema, alertas e performance
     */
    get: operations["RelatoriosController_obterSaudeSistema"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/relatorios/descartes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Relatório de descartes
     * @description Lista todos os descartes de EPIs com filtros avançados e estatísticas
     */
    get: operations["RelatoriosController_relatorioDescartes"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/relatorios/descartes/estatisticas": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Estatísticas de descartes
     * @description Retorna estatísticas resumidas sobre descartes dos últimos 30 dias
     */
    get: operations["RelatoriosController_estatisticasDescartes"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/relatorios/auditoria": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Relatório de auditoria
     * @description Lista operações do sistema para auditoria e compliance
     */
    get: operations["RelatoriosController_relatorioAuditoria"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: never;
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  HealthController_checkHealth: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  HealthController_deployDatabase: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ContratadaController_listarContratadas: {
    parameters: {
      query?: {
        /** @description Filtrar por CNPJ */
        cnpj?: string;
        /** @description Filtrar por nome */
        nome?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Lista de contratadas */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @example true */
            success?: boolean;
            data?: {
              contratadas?: {
                /** Format: uuid */
                id?: string;
                nome?: string;
                cnpj?: string;
                cnpjFormatado?: string;
                /** Format: date-time */
                createdAt?: string;
              }[];
              total?: number;
            };
          };
        };
      };
    };
  };
  ContratadaController_criarContratada: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Contratada criada com sucesso */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @example true */
            success?: boolean;
            data?: {
              /** Format: uuid */
              id?: string;
              /** @example Empresa Contratada LTDA */
              nome?: string;
              /** @example 12345678000190 */
              cnpj?: string;
              /** @example 12.345.678/0001-90 */
              cnpjFormatado?: string;
              /** Format: date-time */
              createdAt?: string;
            };
          };
        };
      };
      /** @description Dados inválidos */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description CNPJ já cadastrado */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ContratadaController_obterEstatisticas: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Estatísticas das contratadas */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @example true */
            success?: boolean;
            data?: {
              total?: number;
              colaboradoresVinculados?: number;
              colaboradoresSemContratada?: number;
              topContratadas?: {
                contratada?: {
                  /** Format: uuid */
                  id?: string;
                  nome?: string;
                  cnpjFormatado?: string;
                };
                totalColaboradores?: number;
              }[];
            };
          };
        };
      };
    };
  };
  ContratadaController_buscarPorNome: {
    parameters: {
      query: {
        /** @description Nome para busca */
        nome: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Resultados da busca */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @example true */
            success?: boolean;
            data?: {
              /** Format: uuid */
              id?: string;
              nome?: string;
              cnpj?: string;
              cnpjFormatado?: string;
              /** Format: date-time */
              createdAt?: string;
            }[];
          };
        };
      };
    };
  };
  ContratadaController_obterContratada: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description ID da contratada */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Dados da contratada */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @example true */
            success?: boolean;
            data?: {
              /** Format: uuid */
              id?: string;
              nome?: string;
              cnpj?: string;
              cnpjFormatado?: string;
              /** Format: date-time */
              createdAt?: string;
            };
          };
        };
      };
      /** @description Contratada não encontrada */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ContratadaController_atualizarContratada: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description ID da contratada */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Contratada atualizada com sucesso */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @example true */
            success?: boolean;
            data?: {
              /** Format: uuid */
              id?: string;
              nome?: string;
              cnpj?: string;
              cnpjFormatado?: string;
              /** Format: date-time */
              createdAt?: string;
            };
          };
        };
      };
      /** @description Dados inválidos */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Contratada não encontrada */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description CNPJ já cadastrado */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ContratadaController_excluirContratada: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description ID da contratada */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Contratada excluída com sucesso */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @example true */
            success?: boolean;
            /** @example Contratada excluída com sucesso */
            message?: string;
          };
        };
      };
      /** @description Não é possível excluir contratada com colaboradores vinculados */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Contratada não encontrada */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  EstoqueController_obterPosicaoEstoque: {
    parameters: {
      query?: {
        /** @description Mostrar apenas itens abaixo do estoque mínimo */
        apenasAbaixoMinimo?: boolean;
        /** @description Mostrar apenas itens com saldo */
        apenasComSaldo?: boolean;
        unidadeNegocioId?: string;
        tipoEpiId?: string;
        almoxarifadoId?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Relatório gerado com sucesso */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @example true */
            success?: boolean;
            data?: {
              itens?: unknown[];
              resumo?: Record<string, never>;
              /** Format: date-time */
              dataGeracao?: string;
            };
          };
        };
      };
    };
  };
  EstoqueController_obterKardex: {
    parameters: {
      query?: {
        dataFim?: string;
        dataInicio?: string;
      };
      header?: never;
      path: {
        almoxarifadoId: string;
        tipoEpiId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Kardex obtido com sucesso */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  EstoqueController_obterAnaliseGiro: {
    parameters: {
      query?: {
        periodo?: "MENSAL" | "TRIMESTRAL" | "SEMESTRAL" | "ANUAL";
        almoxarifadoId?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Análise de giro obtida com sucesso */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  EstoqueController_realizarAjusteDirecto: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Ajuste realizado com sucesso */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            success?: boolean;
            data?: {
              /** Format: uuid */
              movimentacaoId?: string;
              /** Format: uuid */
              tipoEpiId?: string;
              saldoAnterior?: number;
              saldoPosterior?: number;
              diferenca?: number;
              observacoes?: string;
            };
          };
        };
      };
      /** @description Dados inválidos ou permissão negada */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Almoxarifado ou tipo de EPI não encontrado */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  EstoqueController_simularAjuste: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Simulação realizada com sucesso */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  EstoqueController_executarInventario: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Inventário processado com sucesso */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            success?: boolean;
            data?: {
              ajustesRealizados?: unknown[];
              totalItensProcessados?: number;
              totalAjustesPositivos?: number;
              totalAjustesNegativos?: number;
              valorTotalAjustes?: number;
            };
          };
        };
      };
      /** @description Dados inválidos ou permissão negada */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  EstoqueController_validarDivergenciasInventario: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Validação realizada com sucesso */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  EstoqueController_obterHistoricoAjustes: {
    parameters: {
      query?: {
        /** @description Itens por página (padrão: 10, máx: 100) */
        limit?: number;
        /** @description Página (padrão: 1) */
        page?: number;
        dataFim?: string;
        dataInicio?: string;
        tipoEpiId?: string;
        almoxarifadoId?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Histórico obtido com sucesso */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  EstoqueController_obterResumoEstoque: {
    parameters: {
      query?: {
        almoxarifadoId?: string;
        unidadeNegocioId?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Resumo obtido com sucesso */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  EstoqueController_obterAlertasEstoque: {
    parameters: {
      query?: {
        almoxarifadoId?: string;
        unidadeNegocioId?: string;
        severidade?: "BAIXO" | "CRITICO" | "ZERO";
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Alertas obtidos com sucesso */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FichasEpiController_listarFichas: {
    parameters: {
      query?: {
        /** @description Filtrar fichas com devolução em atraso */
        devolucaoPendente?: boolean;
        ativo?: boolean;
        tipoEpiNome?: string;
        colaboradorNome?: string;
        status?: "ATIVA" | "INATIVA" | "SUSPENSA";
        almoxarifadoId?: string;
        tipoEpiId?: string;
        colaboradorId?: string;
        /** @description Itens por página (padrão: 10, máx: 100) */
        limit?: number;
        /** @description Página (padrão: 1) */
        page?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Lista de fichas recuperada com sucesso */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FichasEpiController_criarFicha: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Ficha criada com sucesso */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @example true */
            success?: boolean;
            data?: {
              /** Format: uuid */
              id?: string;
              /** Format: uuid */
              colaboradorId?: string;
              /** Format: uuid */
              tipoEpiId?: string;
              /** Format: uuid */
              almoxarifadoId?: string;
              /** @enum {string} */
              status?: "ATIVA" | "INATIVA" | "SUSPENSA";
            };
          };
        };
      };
      /** @description Dados inválidos */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Ficha já existe para esta combinação */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FichasEpiController_criarOuAtivarFicha: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Ficha criada ou ativada com sucesso */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FichasEpiController_obterEstatisticas: {
    parameters: {
      query?: {
        almoxarifadoId?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Estatísticas obtidas com sucesso */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FichasEpiController_obterFicha: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description ID da ficha */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Ficha encontrada */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Ficha não encontrada */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FichasEpiController_ativarFicha: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Ficha ativada com sucesso */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Ficha já está ativa */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FichasEpiController_inativarFicha: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Ficha inativada com sucesso */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Ficha possui entregas ativas */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FichasEpiController_suspenderFicha: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Ficha suspensa com sucesso */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FichasEpiController_listarEntregasFicha: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Lista de entregas recuperada */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FichasEpiController_criarEntrega: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description ID da ficha */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Entrega criada com sucesso */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            success?: boolean;
            data?: {
              /** Format: uuid */
              id?: string;
              /** Format: date-time */
              dataEntrega?: string;
              status?: string;
              itens?: unknown[];
            };
          };
        };
      };
      /** @description Dados inválidos ou estoque insuficiente */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FichasEpiController_validarEntrega: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Validação realizada */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FichasEpiController_listarEntregasColaborador: {
    parameters: {
      query?: {
        status?:
          | "ATIVA"
          | "DEVOLVIDA_PARCIAL"
          | "DEVOLVIDA_TOTAL"
          | "CANCELADA";
      };
      header?: never;
      path: {
        colaboradorId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Lista de entregas do colaborador */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FichasEpiController_obterPosseAtual: {
    parameters: {
      query?: {
        incluirProximosVencimento?: boolean;
        incluirVencidos?: boolean;
      };
      header?: never;
      path: {
        colaboradorId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Posse atual do colaborador */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FichasEpiController_processarDevolucao: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        entregaId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Devolução processada com sucesso */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            success?: boolean;
            data?: {
              /** Format: uuid */
              entregaId?: string;
              itensDevolucao?: unknown[];
              movimentacoesEstoque?: unknown[];
              statusEntregaAtualizado?: string;
            };
          };
        };
      };
    };
  };
  FichasEpiController_validarDevolucao: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        entregaId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Validação realizada */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FichasEpiController_cancelarDevolucao: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        entregaId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Cancelamento de devolução processado */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FichasEpiController_validarCancelamentoDevolucao: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        entregaId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Validação de cancelamento realizada */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FichasEpiController_obterHistoricoDevolucoes: {
    parameters: {
      query?: {
        colaboradorId?: string;
        tipoEpiId?: string;
        dataInicio?: string;
        dataFim?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Histórico de devoluções obtido */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FichasEpiController_obterHistoricoCancelamentosDevolucao: {
    parameters: {
      query?: {
        colaboradorId?: string;
        tipoEpiId?: string;
        dataInicio?: string;
        dataFim?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Histórico de cancelamentos obtido */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  NotasMovimentacaoController_listarNotas: {
    parameters: {
      query?: {
        dataFim?: string;
        dataInicio?: string;
        status?: "RASCUNHO" | "CONCLUIDA" | "CANCELADA";
        tipo?: "ENTRADA" | "TRANSFERENCIA" | "DESCARTE" | "AJUSTE";
        /** @description Filtrar por número da nota */
        numero?: string;
        /** @description Itens por página (padrão: 10, máx: 100) */
        limit?: number;
        /** @description Página (padrão: 1) */
        page?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Lista de notas recuperada com sucesso */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  NotasMovimentacaoController_criarNota: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Nota criada com sucesso */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @example true */
            success?: boolean;
            data?: {
              /** Format: uuid */
              id?: string;
              /** @example ENT-2024-000001 */
              numero?: string;
              /** @enum {string} */
              tipo?: "ENTRADA" | "TRANSFERENCIA" | "DESCARTE" | "AJUSTE";
              /** @example RASCUNHO */
              status?: string;
            };
          };
        };
      };
      /** @description Dados inválidos */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Almoxarifado não encontrado */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  NotasMovimentacaoController_listarRascunhos: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Rascunhos recuperados com sucesso */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  NotasMovimentacaoController_obterNota: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description ID da nota */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Nota encontrada */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Nota não encontrada */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  NotasMovimentacaoController_atualizarNota: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Nota atualizada com sucesso */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Nota não está em rascunho */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Nota não encontrada */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  NotasMovimentacaoController_excluirNota: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Nota excluída com sucesso */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Nota não pode ser excluída */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Nota não encontrada */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  NotasMovimentacaoController_adicionarItem: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Item adicionado com sucesso */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Dados inválidos ou nota não editável */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Tipo de EPI já adicionado na nota */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  NotasMovimentacaoController_atualizarQuantidadeItem: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description ID da nota */
        id: string;
        /** @description ID do tipo de EPI */
        tipoEpiId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Quantidade atualizada com sucesso */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  NotasMovimentacaoController_removerItem: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description ID da nota */
        id: string;
        /** @description ID do item */
        itemId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Item removido com sucesso */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  NotasMovimentacaoController_concluirNota: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Nota concluída com sucesso */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            success?: boolean;
            data?: {
              notaConcluida?: Record<string, never>;
              movimentacoesCriadas?: unknown[];
              itensProcessados?: unknown[];
            };
          };
        };
      };
      /** @description Nota não pode ser concluída ou estoque insuficiente */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  NotasMovimentacaoController_cancelarNota: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Nota cancelada com sucesso */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Nota não pode ser cancelada */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  NotasMovimentacaoController_validarCancelamento: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Validação realizada */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  RelatoriosController_obterDashboard: {
    parameters: {
      query?: {
        periodo?:
          | "ULTIMO_MES"
          | "ULTIMO_TRIMESTRE"
          | "ULTIMO_SEMESTRE"
          | "ULTIMO_ANO";
        almoxarifadoId?: string;
        unidadeNegocioId?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Dashboard carregado com sucesso */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @example true */
            success?: boolean;
            data?: {
              indicadoresGerais?: unknown[];
              estoqueAlertas?: Record<string, never>;
              entregasRecentes?: Record<string, never>;
              vencimentosProximos?: Record<string, never>;
              episPorCategoria?: Record<string, never>;
              /** Format: date-time */
              dataAtualizacao?: string;
            };
          };
        };
      };
    };
  };
  RelatoriosController_relatorioConformidade: {
    parameters: {
      query?: {
        dataFim?: string;
        dataInicio?: string;
        diasAvisoVencimento?: number;
        incluirProximosVencimento?: boolean;
        incluirVencidos?: boolean;
        colaboradorId?: string;
        unidadeNegocioId?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Relatório de conformidade gerado */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  RelatoriosController_relatorioUsoEpis: {
    parameters: {
      query?: {
        dataFim?: string;
        dataInicio?: string;
        incluirPerdidos?: boolean;
        incluirDevolvidos?: boolean;
        unidadeNegocioId?: string;
        tipoEpiId?: string;
        colaboradorId?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Relatório de uso gerado */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  RelatoriosController_relatorioMovimentacoes: {
    parameters: {
      query?: {
        limit?: number;
        page?: number;
        dataFim?: string;
        dataInicio?: string;
        usuarioId?: string;
        tipoMovimentacao?:
          | "ENTRADA"
          | "SAIDA"
          | "TRANSFERENCIA"
          | "AJUSTE"
          | "DESCARTE"
          | "ESTORNO";
        tipoEpiId?: string;
        almoxarifadoId?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Relatório de movimentações gerado */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  RelatoriosController_obterSaudeSistema: {
    parameters: {
      query?: {
        incluirPerformance?: boolean;
        incluirEstatisticas?: boolean;
        incluirAlertas?: boolean;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Status do sistema obtido */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  RelatoriosController_relatorioDescartes: {
    parameters: {
      query?: {
        responsavelId?: string;
        dataFim?: string;
        dataInicio?: string;
        contratadaId?: string;
        tipoEpiId?: string;
        almoxarifadoId?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Relatório de descartes gerado com sucesso */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  RelatoriosController_estatisticasDescartes: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Estatísticas de descartes obtidas com sucesso */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  RelatoriosController_relatorioAuditoria: {
    parameters: {
      query?: {
        usuarioId?: string;
        acao?: string;
        dataInicio?: string;
        dataFim?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Relatório de auditoria gerado */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
